### ISSUE TITLE
On verify ownership option

### ISSUE THREAD

**Issue by harshvardhanabhinav** [sadityakumar9211/medichain-hardhat#5]
Verification Failed
As per our records 0x9661846C0714E7dB587bCF30739c3aC14b8B52a2 is the owner of this smart contract.
 
How to solve this issue

**Comment by sadityakumar9211** [comment]
Redeploy this smart contract using your own address.

**Comment by harshvardhanabhinav** [comment]
Invalid account: #0 for network: rinkeby - private key too short, expected 32 bytes
  * Invalid account: #1 for network: rinkeby - private key too short, expected 32 bytes
  * Invalid account: #2 for network: rinkeby - private key too short, expected 32 bytes
  * Invalid account: #3 for network: rinkeby - private key too short, expected 32 bytes
  * Invalid account: #0 for network: mainnet - private key too short, expected 32 bytes
  * Invalid account: #1 for network: mainnet - private key too short, expected 32 bytes
  * Invalid account: #2 for network: mainnet - private key too short, expected 32 bytes
  * Invalid account: #3 for network: mainnet - private key too short, expected 32 bytes
  * Invalid account: #0 for network: polygon - private key too short, expected 32 bytes
  * Invalid account: #1 for network: polygon - private key too short, expected 32 bytes
  * Invalid account: #2 for network: polygon - private key too short, expected 32 bytes
  * Invalid account: #3 for network: polygon - private key too short, expected 32 bytes
  * please solve this error after importing private key correctly then also coming

**Comment by harshvardhanabhinav** [comment]
Nothing to compile
 ·------------------------------|--------------|----------------·
 |  Contract Name               ·  Size (KiB)  ·  Change (KiB)  │
 ·······························|··············|·················
 |  DoctorType                  ·       0.084  ·                │
 ·······························|··············|·················
 |  HospitalType                ·       0.084  ·                │
 ·······························|··············|·················
 |  PatientType                 ·       0.084  ·                │
 ·······························|··············|·················
 |  PatientMedicalRecordSystem  ·      13.979  ·                │
 ·------------------------------|--------------|----------------·
failed to get chainId, falling back on net_version...
An unexpected error occurred:

ProviderError: Must be authenticated!
    at HttpProvider.request (E:\medichain-nextjs\medichain-hardhat\node_modules\hardhat\src\internal\core\providers\http.ts:78:19)
    at AutomaticSenderProvider.request (E:\medichain-nextjs\medichain-hardhat\node_modules\hardhat\src\internal\core\providers\accounts.ts:351:34)
    at AutomaticGasProvider.request (E:\medichain-nextjs\medichain-hardhat\node_modules\hardhat\src\internal\core\providers\gas-providers.ts:136:34)       
    at AutomaticGasPriceProvider.request (E:\medichain-nextjs\medichain-hardhat\node_modules\hardhat\src\internal\core\providers\gas-providers.ts:153:36)  
    at ChainIdValidatorProvider._getChainIdFromEthNetVersion (E:\medichain-nextjs\medichain-hardhat\node_modules\hardhat\src\internal\core\providers\chainId.ts:33:45)
    at ChainIdValidatorProvider._getChainId (E:\medichain-nextjs\medichain-hardhat\node_modules\hardhat\src\internal\core\providers\chainId.ts:17:36)      
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ChainIdValidatorProvider.request (E:\medichain-nextjs\medichain-hardhat\node_modules\hardhat\src\internal\core\providers\chainId.ts:55:29)
    at DeploymentsManager.getChainId (E:\medichain-nextjs\medichain-hardhat\node_modules\hardhat-deploy\src\DeploymentsManager.ts:443:23)
    at DeploymentsManager.loadDeployments (E:\medichain-nextjs\medichain-hardhat\node_modules\hardhat-deploy\src\DeploymentsManager.ts:619:17)
error Command failed with exit code 1.
How to solve this issue?

**Comment by sadityakumar9211** [comment]
Which chain are you trying to deploy on?
localhost/ hardhat or goerli?
And is that chain's RPC URL added to your wallet (metamask)?

**Comment by harshvardhanabhinav** [comment]
goerli

**Comment by sadityakumar9211** [comment]
Closing because this version v1 is going to be archived in view of v2 at https://github.com/myriad-org.
